# Generated by Django 5.2.5 on 2025-12-09 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("manual", "手动调整"),
                            ("appeal", "成绩申诉"),
                            ("error", "录入错误"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="调整类型",
                    ),
                ),
                ("reason", models.TextField(verbose_name="调整原因")),
                ("original_value", models.JSONField(verbose_name="原始值")),
                ("new_value", models.JSONField(verbose_name="新值")),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="是否批准"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="处理时间"),
                ),
            ],
            options={
                "verbose_name": "成绩调整记录",
                "verbose_name_plural": "成绩调整记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScoreImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="文件路径"),
                ),
                ("total_rows", models.IntegerField(default=0, verbose_name="总行数")),
                (
                    "success_rows",
                    models.IntegerField(default=0, verbose_name="成功行数"),
                ),
                (
                    "failed_rows",
                    models.IntegerField(default=0, verbose_name="失败行数"),
                ),
                (
                    "error_log",
                    models.TextField(blank=True, null=True, verbose_name="错误日志"),
                ),
                (
                    "column_mapping",
                    models.JSONField(
                        default=dict,
                        help_text="存储Excel列名到系统字段的映射",
                        verbose_name="列映射关系",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("partial", "部分成功"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="导入时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "成绩导入日志",
                "verbose_name_plural": "成绩导入日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_score",
                    models.FloatField(blank=True, null=True, verbose_name="考勤成绩"),
                ),
                (
                    "homework_score",
                    models.FloatField(blank=True, null=True, verbose_name="作业成绩"),
                ),
                (
                    "experiment_score",
                    models.FloatField(blank=True, null=True, verbose_name="实验成绩"),
                ),
                (
                    "review_note_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="复习笔记成绩"
                    ),
                ),
                (
                    "extra_scores",
                    models.JSONField(
                        default=dict,
                        help_text="存储动态成绩字段，如电子笔记、作品、报告等",
                        verbose_name="额外成绩字段",
                    ),
                ),
                (
                    "final_score",
                    models.FloatField(blank=True, null=True, verbose_name="期末成绩"),
                ),
                (
                    "usual_total",
                    models.FloatField(blank=True, null=True, verbose_name="平时总分"),
                ),
                (
                    "final_total",
                    models.FloatField(blank=True, null=True, verbose_name="期末总分"),
                ),
                (
                    "usual_entry",
                    models.FloatField(
                        blank=True,
                        help_text="手动录入的平时成绩，用于最终成绩计算",
                        null=True,
                        verbose_name="平时录入",
                    ),
                ),
                (
                    "final_entry",
                    models.FloatField(
                        blank=True,
                        help_text="手动录入的期末成绩，用于最终成绩计算",
                        null=True,
                        verbose_name="期末录入",
                    ),
                ),
                (
                    "final_grade",
                    models.FloatField(blank=True, null=True, verbose_name="最终成绩"),
                ),
                (
                    "grade_point",
                    models.FloatField(blank=True, null=True, verbose_name="绩点"),
                ),
                (
                    "grade_level",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="等级"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="是否已发布"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否已验证"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "course_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="courses.courseclass",
                        verbose_name="课程班级",
                    ),
                ),
            ],
            options={
                "verbose_name": "成绩记录",
                "verbose_name_plural": "成绩记录",
                "ordering": ["-updated_at"],
            },
        ),
    ]
