# Generated by Django 5.2.5 on 2025-12-09 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("scores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_scores",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="grading_policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.gradingpolicy",
                verbose_name="评分政策",
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to=settings.AUTH_USER_MODEL,
                verbose_name="学生",
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_scores",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddField(
            model_name="scoreadjustment",
            name="adjusted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="调整人",
            ),
        ),
        migrations.AddField(
            model_name="scoreadjustment",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_adjustments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="批准人",
            ),
        ),
        migrations.AddField(
            model_name="scoreadjustment",
            name="score",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjustments",
                to="scores.score",
                verbose_name="成绩记录",
            ),
        ),
        migrations.AddField(
            model_name="scoreimportlog",
            name="course_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.courseclass",
                verbose_name="课程班级",
            ),
        ),
        migrations.AddField(
            model_name="scoreimportlog",
            name="imported_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="导入人",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="score",
            unique_together={("student", "course_class")},
        ),
    ]
