# Generated by Django 5.2.5 on 2026-01-08 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("scores", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gradebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "homework1",
                    models.FloatField(blank=True, null=True, verbose_name="作业1"),
                ),
                (
                    "homework2",
                    models.FloatField(blank=True, null=True, verbose_name="作业2"),
                ),
                (
                    "homework3",
                    models.FloatField(blank=True, null=True, verbose_name="作业3"),
                ),
                (
                    "homework4",
                    models.FloatField(blank=True, null=True, verbose_name="作业4"),
                ),
                (
                    "homework5",
                    models.FloatField(blank=True, null=True, verbose_name="作业5"),
                ),
                (
                    "experiment1",
                    models.FloatField(blank=True, null=True, verbose_name="实验1"),
                ),
                (
                    "experiment2",
                    models.FloatField(blank=True, null=True, verbose_name="实验2"),
                ),
                (
                    "attendance1",
                    models.FloatField(blank=True, null=True, verbose_name="考勤1"),
                ),
                (
                    "attendance2",
                    models.FloatField(blank=True, null=True, verbose_name="考勤2"),
                ),
                (
                    "attendance3",
                    models.FloatField(blank=True, null=True, verbose_name="考勤3"),
                ),
                (
                    "attendance4",
                    models.FloatField(blank=True, null=True, verbose_name="考勤4"),
                ),
                (
                    "attendance5",
                    models.FloatField(blank=True, null=True, verbose_name="考勤5"),
                ),
                (
                    "review_note",
                    models.FloatField(blank=True, null=True, verbose_name="复习笔记"),
                ),
                (
                    "final_score",
                    models.FloatField(blank=True, null=True, verbose_name="期末成绩"),
                ),
                (
                    "usual_score",
                    models.FloatField(blank=True, null=True, verbose_name="平时成绩"),
                ),
                (
                    "total_score",
                    models.FloatField(blank=True, null=True, verbose_name="总评成绩"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "course_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gradebooks",
                        to="courses.courseclass",
                        verbose_name="课程班级",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_gradebooks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gradebooks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_gradebooks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "记分册",
                "verbose_name_plural": "记分册",
                "ordering": ["-updated_at"],
                "unique_together": {("student", "course_class")},
            },
        ),
    ]
