# Generated by Django 5.2.5 on 2026-01-09 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("scores", "0003_gradebook"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgorithmScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_performance",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课堂表现（考勤平均）"
                    ),
                ),
                (
                    "note_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="笔记（复习笔记）"
                    ),
                ),
                (
                    "homework_avg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="作业（作业平均）"
                    ),
                ),
                (
                    "experiment_avg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="实验（实验平均）"
                    ),
                ),
                (
                    "usual_score",
                    models.FloatField(blank=True, null=True, verbose_name="平时成绩"),
                ),
                ("M1", models.FloatField(blank=True, null=True, verbose_name="M1/35")),
                ("M2", models.FloatField(blank=True, null=True, verbose_name="M2/20")),
                (
                    "M3",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="M3/35（存储35分制，计算时按31分制）",
                    ),
                ),
                ("M4", models.FloatField(blank=True, null=True, verbose_name="M4/10")),
                (
                    "final_paper_score",
                    models.FloatField(blank=True, null=True, verbose_name="卷面成绩"),
                ),
                (
                    "obj1_classroom",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标1-课堂"
                    ),
                ),
                (
                    "obj1_note",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标1-笔记"
                    ),
                ),
                (
                    "obj1_homework",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标1-作业"
                    ),
                ),
                (
                    "obj1_experiment",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标1-实验"
                    ),
                ),
                (
                    "obj1_final",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标1-期末"
                    ),
                ),
                (
                    "obj1_achievement",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标1-达成情况"
                    ),
                ),
                (
                    "obj1_degree",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标1-达成度"
                    ),
                ),
                (
                    "obj2_classroom",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标2-课堂"
                    ),
                ),
                (
                    "obj2_note",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标2-笔记"
                    ),
                ),
                (
                    "obj2_homework",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标2-作业"
                    ),
                ),
                (
                    "obj2_experiment",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标2-实验"
                    ),
                ),
                (
                    "obj2_final",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标2-期末"
                    ),
                ),
                (
                    "obj2_achievement",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标2-达成情况"
                    ),
                ),
                (
                    "obj2_degree",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标2-达成度"
                    ),
                ),
                (
                    "obj3_classroom",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标3-课堂"
                    ),
                ),
                (
                    "obj3_note",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标3-笔记"
                    ),
                ),
                (
                    "obj3_homework",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标3-作业"
                    ),
                ),
                (
                    "obj3_experiment",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标3-实验"
                    ),
                ),
                (
                    "obj3_final",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标3-期末"
                    ),
                ),
                (
                    "obj3_achievement",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标3-达成情况"
                    ),
                ),
                (
                    "obj3_degree",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标3-达成度"
                    ),
                ),
                (
                    "obj4_classroom",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标4-课堂"
                    ),
                ),
                (
                    "obj4_note",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标4-笔记"
                    ),
                ),
                (
                    "obj4_homework",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标4-作业"
                    ),
                ),
                (
                    "obj4_experiment",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标4-实验"
                    ),
                ),
                (
                    "obj4_final",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标4-期末"
                    ),
                ),
                (
                    "obj4_achievement",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标4-达成情况"
                    ),
                ),
                (
                    "obj4_degree",
                    models.FloatField(
                        blank=True, null=True, verbose_name="课程目标4-达成度"
                    ),
                ),
                (
                    "total_score",
                    models.FloatField(blank=True, null=True, verbose_name="总成绩"),
                ),
                (
                    "usual_entry",
                    models.FloatField(blank=True, null=True, verbose_name="平时录入"),
                ),
                (
                    "final_entry",
                    models.FloatField(blank=True, null=True, verbose_name="期末录入"),
                ),
                (
                    "final_grade",
                    models.FloatField(blank=True, null=True, verbose_name="最终成绩"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "course_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="algorithm_scores",
                        to="courses.courseclass",
                        verbose_name="课程班级",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_algorithm_scores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "gradebook",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="algorithm_score",
                        to="scores.gradebook",
                        verbose_name="记分册",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="algorithm_scores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_algorithm_scores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "算法分析与设计成绩",
                "verbose_name_plural": "算法分析与设计成绩",
                "ordering": ["-updated_at"],
                "unique_together": {("student", "course_class")},
            },
        ),
    ]
