# Generated by Django 5.2.5 on 2026-01-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0004_algorithmscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithmscore",
            name="raw_paper_scores",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="原始卷面成绩数据（小题得分）",
            ),
        ),
    ]
