# Generated by Django 5.2.5 on 2026-05-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0003_gradebook"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradebook",
            name="conclusion",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="结论"
            ),
        ),
        migrations.AddField(
            model_name="gradebook",
            name="report_score",
            field=models.FloatField(blank=True, null=True, verbose_name="报告"),
        ),
        migrations.AddField(
            model_name="gradebook",
            name="system_score",
            field=models.FloatField(blank=True, null=True, verbose_name="系统"),
        ),
    ]
