# Generated by Django 5.2.5 on 2025-12-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="课程代码"
                    ),
                ),
                (
                    "course_name",
                    models.CharField(max_length=200, verbose_name="课程名称"),
                ),
                (
                    "english_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="英文名称"
                    ),
                ),
                ("credit", models.FloatField(verbose_name="学分")),
                ("hours", models.IntegerField(verbose_name="学时")),
                (
                    "department",
                    models.CharField(max_length=100, verbose_name="开课院系"),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("spring", "春季学期"),
                            ("autumn", "秋季学期"),
                            ("summer", "夏季学期"),
                            ("winter", "冬季学期"),
                        ],
                        max_length=20,
                        verbose_name="开课学期",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="开课年份")),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="是否必修"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="课程描述"),
                ),
                (
                    "syllabus_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="syllabus/",
                        verbose_name="教学大纲文件",
                    ),
                ),
                (
                    "course_objectives",
                    models.JSONField(
                        default=list,
                        help_text="存储课程目标1、2、3的配置信息，包括权重、计算公式等",
                        verbose_name="课程目标配置",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程管理",
                "ordering": ["-year", "semester", "course_code"],
            },
        ),
        migrations.CreateModel(
            name="CourseClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_name",
                    models.CharField(max_length=50, verbose_name="班级名称"),
                ),
                (
                    "max_students",
                    models.IntegerField(default=100, verbose_name="最大学生数"),
                ),
                (
                    "class_time",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="上课时间"
                    ),
                ),
                (
                    "classroom",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="教室"
                    ),
                ),
            ],
            options={
                "verbose_name": "课程班级",
                "verbose_name_plural": "课程班级",
            },
        ),
        migrations.CreateModel(
            name="CourseObjectiveAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "objective_number",
                    models.IntegerField(
                        choices=[(1, "课程目标1"), (2, "课程目标2"), (3, "课程目标3")],
                        verbose_name="课程目标编号",
                    ),
                ),
                ("usual_score", models.FloatField(default=0, verbose_name="平时得分")),
                (
                    "experiment_score",
                    models.FloatField(default=0, verbose_name="实验得分"),
                ),
                ("final_score", models.FloatField(default=0, verbose_name="期末得分")),
                (
                    "achievement_score",
                    models.FloatField(default=0, verbose_name="达成情况"),
                ),
                (
                    "achievement_degree",
                    models.FloatField(default=0, verbose_name="达成度"),
                ),
                ("max_score", models.FloatField(default=31, verbose_name="目标满分")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "课程目标达成度",
                "verbose_name_plural": "课程目标达成度",
                "ordering": ["objective_number"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="选课时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否在修"),
                ),
            ],
            options={
                "verbose_name": "选课记录",
                "verbose_name_plural": "选课记录",
            },
        ),
        migrations.CreateModel(
            name="GradingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usual_weight",
                    models.FloatField(default=0.3, verbose_name="平时分比例"),
                ),
                (
                    "final_weight",
                    models.FloatField(default=0.7, verbose_name="期末分比例"),
                ),
                (
                    "attendance_weight",
                    models.FloatField(default=0.2, verbose_name="考勤权重"),
                ),
                (
                    "homework_weight",
                    models.FloatField(default=0.3, verbose_name="作业权重"),
                ),
                (
                    "experiment_weight",
                    models.FloatField(default=0.3, verbose_name="实验权重"),
                ),
                (
                    "review_note_weight",
                    models.FloatField(default=0.2, verbose_name="复习笔记权重"),
                ),
                (
                    "grading_scale",
                    models.JSONField(default=dict, verbose_name="评分标准"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "成绩评定政策",
                "verbose_name_plural": "成绩评定政策",
            },
        ),
    ]
