# Generated by Django 5.2.5 on 2025-12-09 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("scores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teachers",
            field=models.ManyToManyField(
                limit_choices_to={"user_type": "teacher"},
                related_name="courses_taught",
                to=settings.AUTH_USER_MODEL,
                verbose_name="授课教师",
            ),
        ),
        migrations.AddField(
            model_name="courseclass",
            name="assistant_teachers",
            field=models.ManyToManyField(
                blank=True,
                related_name="assistant_classes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="助教",
            ),
        ),
        migrations.AddField(
            model_name="courseclass",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="courseclass",
            name="main_teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_classes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="主讲教师",
            ),
        ),
        migrations.AddField(
            model_name="courseobjectiveachievement",
            name="score",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objective_achievements",
                to="scores.score",
                verbose_name="成绩记录",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="course_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courseclass",
                verbose_name="课程班级",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="学生",
            ),
        ),
        migrations.AddField(
            model_name="courseclass",
            name="students",
            field=models.ManyToManyField(
                related_name="enrolled_classes",
                through="courses.Enrollment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="选课学生",
            ),
        ),
        migrations.AddField(
            model_name="gradingpolicy",
            name="course",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grading_policy",
                to="courses.course",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseobjectiveachievement",
            unique_together={("score", "objective_number")},
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "course_class")},
        ),
        migrations.AlterUniqueTogether(
            name="courseclass",
            unique_together={("course", "class_name")},
        ),
    ]
