# Generated by Django 5.2.5 on 2026-01-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseclass",
            name="m_calculation_config",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="M1/M2/M3/M4计算配置"
            ),
        ),
    ]
